// <auto-generated />
using System;
using CoachTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoachTracker.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316142235_SyncAppDbContext")]
    partial class SyncAppDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CoachTracker.Api.Features.Exercises.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPlannedSets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipment")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementPatternTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMuscle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMuscles")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "incline press",
                            Name = "incline sm press",
                            PrimaryMuscle = "upperchest"
                        },
                        new
                        {
                            Id = 2,
                            DefaultPlannedSets = 2,
                            Equipment = "pec-deck mach",
                            MovementPatternTag = "horizontal abbduction",
                            Name = "pec-deck",
                            PrimaryMuscle = "chest"
                        },
                        new
                        {
                            Id = 3,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "vertical press",
                            Name = "oh press",
                            PrimaryMuscle = "side-delts"
                        },
                        new
                        {
                            Id = 4,
                            DefaultPlannedSets = 3,
                            Equipment = "belt",
                            MovementPatternTag = "Vertical Pull",
                            Name = "weighted p-up",
                            PrimaryMuscle = "lats"
                        },
                        new
                        {
                            Id = 5,
                            DefaultPlannedSets = 2,
                            Equipment = "machine",
                            MovementPatternTag = "Vertical Pull",
                            Name = "l_pd(wg)",
                            PrimaryMuscle = "lats"
                        },
                        new
                        {
                            Id = 6,
                            DefaultPlannedSets = 2,
                            Equipment = "cable/bench",
                            MovementPatternTag = "overhead extension",
                            Name = "seated cable triceps oh extension",
                            PrimaryMuscle = "tceps longhead"
                        },
                        new
                        {
                            Id = 7,
                            DefaultPlannedSets = 2,
                            Equipment = "cable",
                            MovementPatternTag = "lateral raise",
                            Name = "cable cuff lraise",
                            PrimaryMuscle = "side-delts"
                        },
                        new
                        {
                            Id = 8,
                            DefaultPlannedSets = 2,
                            Equipment = "dumbell",
                            MovementPatternTag = "curl",
                            Name = "seated incline curl",
                            PrimaryMuscle = "bceps"
                        },
                        new
                        {
                            Id = 9,
                            DefaultPlannedSets = 2,
                            Equipment = "machine",
                            MovementPatternTag = "horizontal pull",
                            Name = "upper-back row",
                            PrimaryMuscle = "upper-back"
                        },
                        new
                        {
                            Id = 10,
                            DefaultPlannedSets = 2,
                            Equipment = "machine",
                            MovementPatternTag = "scapular regression",
                            Name = "kelso shrug",
                            PrimaryMuscle = "traps"
                        },
                        new
                        {
                            Id = 11,
                            DefaultPlannedSets = 2,
                            Equipment = "cable",
                            MovementPatternTag = "sagital pull",
                            Name = "narrow grip latfocusedsinglearm row",
                            PrimaryMuscle = "lats"
                        },
                        new
                        {
                            Id = 12,
                            DefaultPlannedSets = 2,
                            Equipment = "dumbell",
                            MovementPatternTag = "curl",
                            Name = "preachers",
                            PrimaryMuscle = "bceps"
                        },
                        new
                        {
                            Id = 13,
                            DefaultPlannedSets = 2,
                            Equipment = "pec-deck machine",
                            MovementPatternTag = "rear-delt iso",
                            Name = "buttaflies",
                            PrimaryMuscle = "rear-delts"
                        },
                        new
                        {
                            Id = 14,
                            DefaultPlannedSets = 2,
                            Equipment = "belt",
                            MovementPatternTag = "dips",
                            Name = "weighteddips",
                            PrimaryMuscle = "chest"
                        },
                        new
                        {
                            Id = 15,
                            DefaultPlannedSets = 2,
                            Equipment = "Cable",
                            MovementPatternTag = "Elbow Extension",
                            Name = "Tricep Extensions",
                            PrimaryMuscle = "Triceps"
                        },
                        new
                        {
                            Id = 16,
                            DefaultPlannedSets = 2,
                            Equipment = "machine",
                            MovementPatternTag = "extension",
                            Name = "leg xtension",
                            PrimaryMuscle = "quads"
                        },
                        new
                        {
                            Id = 17,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "sm bulgarians",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 18,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "hipaBBductor",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 19,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "hipadDuctor",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 20,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "baxktension",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 21,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "calf",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 22,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "cable crunch",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 23,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "singlearm tpushdown",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 24,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "forearms(r/k)",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 25,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "takanakas",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 26,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "bushi",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 27,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "horshi",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 28,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "dogshi",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 29,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "yadi",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 30,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "yaddi",
                            PrimaryMuscle = "legs"
                        },
                        new
                        {
                            Id = 31,
                            DefaultPlannedSets = 2,
                            Equipment = "smith machine",
                            MovementPatternTag = "squat pattern",
                            Name = "yadda",
                            PrimaryMuscle = "legs"
                        });
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Nutrition.NutritionFoodLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("C")
                        .HasColumnType("REAL");

                    b.Property<string>("DayKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("F")
                        .HasColumnType("REAL");

                    b.Property<int>("FdcId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Grams")
                        .HasColumnType("REAL");

                    b.Property<double>("Kcal")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("P")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DayKey");

                    b.ToTable("NutritionFoodLogs");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Nutrition.NutritionUsual", b =>
                {
                    b.Property<int>("FdcId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("C")
                        .HasColumnType("REAL");

                    b.Property<double>("F")
                        .HasColumnType("REAL");

                    b.Property<double>("Grams")
                        .HasColumnType("REAL");

                    b.Property<double>("Kcal")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("P")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("FdcId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("NutritionUsuals");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.PlannedCalendarDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("SplitDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.HasIndex("SplitDayId");

                    b.ToTable("PlannedCalendarDays");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.Split", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Splits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "torso / limbs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "upper / lower"
                        },
                        new
                        {
                            Id = 3,
                            Name = "anterior / posterior"
                        },
                        new
                        {
                            Id = 4,
                            Name = "push / pull / legs"
                        });
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.SplitDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SplitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SplitId");

                    b.ToTable("SplitDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "torso",
                            OrderIndex = 0,
                            SplitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "limbs",
                            OrderIndex = 1,
                            SplitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "upper",
                            OrderIndex = 0,
                            SplitId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "lower",
                            OrderIndex = 1,
                            SplitId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "anterior",
                            OrderIndex = 0,
                            SplitId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "posterior",
                            OrderIndex = 1,
                            SplitId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "push",
                            OrderIndex = 0,
                            SplitId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "pull",
                            OrderIndex = 1,
                            SplitId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "legs",
                            OrderIndex = 2,
                            SplitId = 4
                        });
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.SplitDayExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SplitDayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetRepRange")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SplitDayId");

                    b.ToTable("SplitDayExercises");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Storage.KeyValueEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.DailyWorkout", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("DailyWorkouts");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DailyWorkoutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormQuality")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rir")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DailyWorkoutDate");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.PlannedCalendarDay", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Splits.SplitDay", "SplitDay")
                        .WithMany()
                        .HasForeignKey("SplitDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SplitDay");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.SplitDay", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Splits.Split", "Split")
                        .WithMany("Days")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Split");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.SplitDayExercise", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachTracker.Api.Features.Splits.SplitDay", "SplitDay")
                        .WithMany("Exercises")
                        .HasForeignKey("SplitDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("SplitDay");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutSet", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Workouts.DailyWorkout", "DailyWorkout")
                        .WithMany("Sets")
                        .HasForeignKey("DailyWorkoutDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachTracker.Api.Features.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyWorkout");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.Split", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Splits.SplitDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.DailyWorkout", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
