// <auto-generated />
using System;
using CoachTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoachTracker.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311132716_RebuildInitialSchema")]
    partial class RebuildInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CoachTracker.Api.Features.Exercises.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Plans.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Plans.TrainingPlanDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingPlanDays");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Plans.TrainingPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetReps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingPlanDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingPlanDayId");

                    b.ToTable("TrainingPlanItems");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutExerciseLogs");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutSetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rir")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutExerciseLogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseLogId");

                    b.ToTable("WorkoutSetLogs");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Plans.TrainingPlanDay", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Plans.TrainingPlan", "TrainingPlan")
                        .WithMany("Days")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Plans.TrainingPlanItem", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachTracker.Api.Features.Plans.TrainingPlanDay", "TrainingPlanDay")
                        .WithMany("Items")
                        .HasForeignKey("TrainingPlanDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingPlanDay");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutExerciseLog", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Workouts.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutSetLog", b =>
                {
                    b.HasOne("CoachTracker.Api.Features.Workouts.WorkoutExerciseLog", "WorkoutExerciseLog")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExerciseLog");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Plans.TrainingPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Plans.TrainingPlanDay", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutExerciseLog", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("CoachTracker.Api.Features.Workouts.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
